[package]
name = "rust-bitcoin-accounting-utxo-to-fasbi"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1.30", features = ["serde"] }
rust_decimal_macros = "1.30"
serde = { version = "1.0", features = ["derive"] }
